config/routes.rb
Securitylogbook::Application.routes.draw do
  devise_for :users
  resources :log_records

  resources :offices
  root to: "pages#index"

end

app/models/log_record.rb
class LogRecord < ActiveRecord::Base
	belongs_to :office
	belongs_to :user
end

app/models/office.rb
class Office < ActiveRecord::Base
	has_many :log_records

	def to_s
		"#{name}"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	def to_s
		"#{email}"
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/log_records_controller.rb
class LogRecordsController < ApplicationController
  #before_action :set_log_record, only: [:show, :edit, :update, :destroy]

  # GET /log_records
  def index
    @log_records = LogRecord.all
  end

  # GET /log_records/1
  def show
    @log_record = LogRecord.find(params[:id])
  end

  # GET /log_records/new
  def new
    @log_record = LogRecord.new
  

  end

  # GET /log_records/1/edit
  def edit
     @log_record = LogRecord.find(params[:id])
  end

  # POST /log_records
  def create
    @log_record = LogRecord.new(log_record_params)
    @log_record.user = current_user
   
      if @log_record.save
        redirect_to @log_record, notice: 'Log record was successfully created.' 
        
      else
        render action: 'new'         
      end
    
  end

  # PATCH/PUT /log_records/1
  def update
     @log_record = LogRecord.find(params[:id])
      if @log_record.update(log_record_params)
        redirect_to @log_record, notice: 'Log record was successfully updated.' 
        
      else
        render action: 'edit' 
  
      end
   
  end

  # DELETE /log_records/1
  def destroy
    @log_record = LogRecord.find(params[:id])
    @log_record.destroy
     redirect_to log_records_url   

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log_record
      @log_record = LogRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_record_params
      params.require(:log_record).permit!
    end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  #before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  def index
    @offices = Office.all
  end

  # GET /offices/1
  def show
    @office = Office.find(params[:id])
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
    @office = Office.find(params[:id])
  end

  # POST /offices
  def create
    @office = Office.new(office_params)

      if @office.save
       redirect_to @office, notice: 'Office was successfully created.' 
       
      else
        render action: 'new'
        
      end
   
  end

  # PATCH/PUT /offices/1
  def update
    @office = Office.find(params[:id])
      if @office.update(office_params)
        redirect_to @office, notice: 'Office was successfully updated.'
      
      else
        render action: 'edit' 
      end
  end

  # DELETE /offices/1
  def destroy
    @office = Office.find(params[:id])
    @office.destroy
    redirect_to offices_path 
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit!
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	before_filter :authenticate_user!

	 def index
   redirect_to offices_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Security Log Book</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <% if user_signed_in? %>
          <%= render partial: "shared/offnav" %>
        <% else %>
          <%= render partial: "shared/nav" %>
        <% end %>

        

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/log_records/_form.html.erb
<div class="div-center-wide panel panel-default">
<%= simple_form_for(@log_record, defaults: { wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' } }) do |f| %>

 <%= f.association :user,  prompt: "#{current_user}", disabled: true %>
  <%= f.input :visitor_name %>
      <%= f.association :office, prompt: "Choose Office" %>
  <%= f.input :purpose_of_visit %>
  <%= f.input :time_of_visit, as: :datetime, start_year: Date.today.year - 50, end_year: Date.today.year, order: [:month, :day, :year] , input_html: { class: 'date-time' }%>


  <hr>
  <%= f.submit "Save Record", class: "btn btn-primary" %>
<% end %>
</div>

app/views/log_records/edit.html.erb
<h1>Editing Log Record/h1>

<%= render 'form' %>

<%= link_to ' ', @log_record, class: "btn btn-info glyphicon glyphicon-zoom-in" %> 
<%= link_to ' ', log_records_path, class: "btn btn-success glyphicon glyphicon-backward" %>

app/views/log_records/index.html.erb
<div class="content">
<h1>All Log Records</h1>
  <hr>
  <table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Visitor name</th>
      <th>Purpose of visit</th>
      <th>Time of visit</th>
      <th>Office</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @log_records.each do |log_record| %>
      <tr>
        <td><%= log_record.user %></td>
        <td><%= log_record.visitor_name %></td>
                <td>
          <%= log_record.office %>
        </td>
        <td><%= log_record.purpose_of_visit %></td>
        <td><%= log_record.time_of_visit %></td>

        <td><%= link_to 'Show', log_record, class: "btn btn-xs btn-default" %>
       <%= link_to 'Edit', edit_log_record_path(log_record), class: "btn btn-xs btn-default" %>
        <%= link_to 'Delete', log_record, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log Record', new_log_record_path, class: "btn btn-lg btn-success" %>

</div>

app/views/log_records/new.html.erb
<h1>New Log Record</h1>

<%= render 'form' %>

<%= link_to ' ', log_records_path, class: "btn btn-lg btn-success glyphicon glyphicon-backward" %>

app/views/log_records/show.html.erb
<div class="div-center-wide panel panel-default">
<p id="notice"><%= notice %></p>

<table class="table table-bordered">
 
    <tr>
    <td class="label-show"> User </td>
    <td>(<%= @log_record.user_id %>)
    <%= @log_record.user %></td>
    </tr>

    <tr>
    <td class="label-show"> Visitor Name </td>
    <td> <%= @log_record.visitor_name %></td>
    </tr>

    <tr>
    <td class="label-show"> Office </td>
    <td>  (<%= @log_record.office_id %>)
  <%= @log_record.office %></td>
    </tr>

    <tr>
    <td class="label-show"> Purpose of Visit </td>
    <td>  <%= @log_record.purpose_of_visit %></td>
    </tr>

    <tr>
    <td class="label-show"> Time of Visit </td>
    <td> <%= @log_record.time_of_visit %></td>
    </tr>



</table>


<div class="pull-right">

<%= link_to 'Edit', edit_log_record_path(@log_record), class: "btn btn-sm btn-info" %> 
<%= link_to 'Back', log_records_path, class: "btn btn-sm btn-success"%>
</div>
<br>
</div>

app/views/offices/_form.html.erb
<div class="div-center-wide panel panel-default">
<%= simple_form_for(@office, defaults: { wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' } }) do |f| %>
  <%= f.input :name %>
  <%= f.input :room_number %>
  <%= f.input :description %>

  <hr>
  <%= f.submit "Save Office", class: "btn btn-primary" %>

<% end %>
</div>

app/views/offices/edit.html.erb
<h1>Editing office</h1>

<%= render 'form' %>

<%= link_to ' ', @office, class: "btn btn-info glyphicon glyphicon-zoom-in" %>
<%= link_to ' ', offices_path, class: "btn btn-success glyphicon glyphicon-backward"  %>

app/views/offices/index.html.erb
<div class="content">
<h1>All Offices</h1>
<hr>
  <table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Room number</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= office.name %></td>
        <td><%= office.room_number %></td>
        <td><%= office.description %></td>
        <td><%= link_to 'Show', office, class: "btn btn-xs btn-default" %>
       <%= link_to 'Edit', edit_office_path(office.id), class: "btn btn-xs btn-default"  %>
       <%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Office', new_office_path, class: "btn btn-lg btn-success" %>
</div>

app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form' %>

<%= link_to ' ', offices_path, class: "btn btn-lg btn-success glyphicon glyphicon-backward" %>

app/views/offices/show.html.erb
<div class="div-center-wide panel panel-default">
<p id="notice"><%= notice %></p>

<table class="table table-bordered">
 
    <tr>
    <td class="label-show"> Name</td>
    <td>  <%= @office.name %></td>
    </tr>

    <tr>
    <td class="label-show"> Room Number </td>
    <td> <%= @office.room_number %></td>
    </tr>

    <tr>
    <td class="label-show"> Description </td>
    <td>   <%= @office.description %></td>
    </tr>


</table>

<div class="pull-right">
<%= link_to 'Edit', edit_office_path(@office), class: "btn btn-sm btn-info" %> 
<%= link_to 'Back', offices_path, class: "btn btn-sm btn-success"%>
</div>
<br>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">Security Log Book</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        
        <li>
          <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_user_session_path)  %>  
          </li>
        <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/shared/_offnav.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">Security Log Book</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Offices <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add Office", new_office_path %></li>
            <li><%= link_to "All Offices", offices_path %></li>
          </ul>
        </li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Log Records <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add Log Record", new_log_record_path %></li>
            <li><%= link_to "All Log Records", log_records_path %></li>
          </ul>
        </li>
  
        <li>
          <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_user_session_path)  %>  
          </li>
        <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div>
</nav>